// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetSettings():Promise<main.Settings>;

export function GetStatus():Promise<main.Status>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function StartService():Promise<void>;

export function StopService():Promise<void>;
