// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}
